CREATE TABLE [Message](
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	[DeviceName] NVARCHAR(128) NULL,
	[Topic] NVARCHAR(MAX) NOT NULL,
	[Content] NVARCHAR(MAX) NOT NULL,
	DeliverAt DATETIME NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateBy NVARCHAR(48) NOT NULL,
    DeleteAt DATETIME NULL,
    DeleteBy NVARCHAR(48) NULL,
    UpdateAt DATETIME NULL,
    UpdateBy NVARCHAR(48) NULL
);