CREATE TABLE [DeviceValue](
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    DeviceId UNIQUEIDENTIFIER NOT NULL,
	[DeviceName] NVARCHAR(128) NULL,
	[CorrelationId] NVARCHAR(MAX) NOT NULL,
	[Key] NVARCHAR(MAX) NOT NULL,
	[Value] NVARCHAR(MAX) NOT NULL,
    [ValueType] NVARCHAR(MAX) NOT NULL,
	DeliverAt DATETIME NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateBy NVARCHAR(48) NOT NULL,
    DeleteAt DATETIME NULL,
    DeleteBy NVARCHAR(48) NULL,
    UpdateAt DATETIME NULL,
    UpdateBy NVARCHAR(48) NULL
);